baseURL: "https://ikso.us/"
languageCode: "en-us"
title: "Trenton Broughton"
theme: "ikso"
PygmentsCodeFences: true
params:
  description: "danger: high entropy"
markup:
  goldmark:
    renderer:
      unsafe: true
