# Hugo build!
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: monachus/hugo
    working_directory: /site
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: hugo
