baseURL = 'https://ikso.us/'
languageCode = 'en-us'
title = 'ikso theme'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
