name: CI

on: 
  push:
    branches:
      - content
jobs:
  build:
    runs-on: ubuntu-latest
    container: trenton/hugo-extended
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
      with:
        ref: master
        path: ./trenton42.github.com/public
    - name: What is here?
      run: ls -l
    - name: What does uses do?
      uses: docker://trenton/hugo-extended
    - name: List again
      run: ls -l
