name: CI

on: 
  push:
    branches:
      - content
jobs:
  build:
    runs-on: ubuntu-latest
    container: trenton/hugo-extended
    steps:
    - uses: actions/checkout@v1
      with:
        path: ./site
    - name: Look
      run: ls && ls site
    - uses: actions/checkout@v1
      with:
        ref: master
        path: ./public
    - name: Get public
      run: ls && ls public
    - name: Run Hugo
      run: hugo --cleanDestinationDir -d /public
    - name: Get Build Status
      run: cd public && git status --porcelain
