name: Blagh-o-matic

on: 
  push:
    branches:
      - content
jobs:
  build:
    runs-on: ubuntu-latest
    container: trenton/hugo-extended
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout public
      uses: actions/checkout@v2
      with:
        path: public
        ref: master
    - name: Run Hugo
      run: hugo --cleanDestinationDir -d public
    - name: Publish
      run: cd public && test -n "$(git status --porcelain)" && ( git add . && git commit -m "Updated content" && git push ) || echo "Nothing to do"
