name: CI

on: 
  push:
    branches:
      - content
jobs:
  build:
    runs-on: ubuntu-latest
    container: trenton/hugo-extended
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout public
      uses: actions/checkout@v2
      with:
        path: public
        branch: master
    - name: Get public
      run: pwd && ls && ls ..
    - name: Run Hugo
      run: hugo --cleanDestinationDir -d /public
    - name: Get Build Status
      run: cd public && git status --porcelain
