name: CI

on: 
  push:
    branches:
      - content
jobs:
  build:
    runs-on: ubuntu-latest
    container: trenton/hugo-extended
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
      with:
        ref: master
        path: ./public
    - name: What is here?
      run: cd .. && ls -l && pwd
    - name: Run Hugo
      run: hugo --cleanDestinationDir -d /public
    - name: Get Build Status
      run: cd public && git status --porcelain
