name: CI

on: 
  push:
    branches:
      - content
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Where are we?
      run: pwd
    - name: What is here?
      run: ls -l
    - name: What does uses do?
      uses: docker://trenton/hugo-extended
    - name: List again
      run: ls -l
