name: CI

on: 
  push:
    branches:
      - content
jobs:
  build:
    runs-on: ubuntu-latest
    container: trenton/hugo-extended
    steps:
    - uses: actions/checkout@v1
    - name: Get public
      run: ls && mkdir -p public && cd public && git clone --single-branch --branch master git@github.com:trenton42/trenton42.github.io.git
    - name: Run Hugo
      run: hugo --cleanDestinationDir -d /public
    - name: Get Build Status
      run: cd public && git status --porcelain
